### ISSUE TITLE
Deprecated

### ISSUE THREAD

**Issue by tlhunter** [opentable/hapi-ot-logger#35]
I believe this project should be deprecated in favor of https://github.com/opentable/ot-logger-hapi-middleware

Can we modify the readme and the github subject?

**Comment by ArnoldZokas** [comment]
Yes, that.s right. This is done: https://github.com/opentable/hapi-ot-logger/pull/36
We are in the process of migrating remaining consumers. Once that is complete - this repo will be purged.
