### ISSUE TITLE
Tests rely on previous tests, setTimeouts

### ISSUE THREAD

**Issue by tlhunter** [opentable/hapi-ot-logger#6]
Each test in the test suite relies on the test before it passing. This makes it impossible to test small pieces of code with .only or .skip.

Also, the tests use setTimeout calls before making assertions. Ideally they would know when the actual work is complete then test the conditions.

**Comment by ArnoldZokas** [comment]
Fixed in https://github.com/opentable/hapi-ot-logger/commit/bfd9b063a2f09e23452aec89e9cd3ff4fb70c7dd
