### ISSUE TITLE
Tests check raw REDIS commands

### ISSUE THREAD

**Issue by tlhunter** [opentable/hapi-ot-logger#7]
Tests shouldn't check raw REDIS commands sent over the wire. Consider the following check:

```js
if (d.indexOf("rpush\r\n") > -1) {}
```

The test relies too heavily on Redis internals, e.g. if the client were to send `RPUSH`, which is also valid, the test suite would fail. Instead we should use something like sinon to make sure the right redis client methods are called.

**Comment by ArnoldZokas** [comment]
Fixed in: https://github.com/opentable/hapi-ot-logger/commit/bfd9b063a2f09e23452aec89e9cd3ff4fb70c7dd
